/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buoi2.bai1;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS TUF
 */
public class from extends javax.swing.JFrame {

    /**
     * Creates new form from
     */
    Date date=null;
    ArrayList<SinhVien> dsSinhVien=new ArrayList<>();
   
    SimpleDateFormat sdf=new SimpleDateFormat("dd/mm/yyyy");
    public from() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMasv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        cbgioitinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtdiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdonvi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txthocphi = new javax.swing.JTextField();
        rdsvhttt = new javax.swing.JRadioButton();
        rdsvmm = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Sinh Viên:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ SINH VIÊN");

        txtMasv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMasvFocusLost(evt);
            }
        });
        txtMasv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasvActionPerformed(evt);
            }
        });

        jLabel3.setText("Họ Tên:");

        txtHoten.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHotenFocusLost(evt);
            }
        });

        jLabel4.setText("Ngày Sinh:");

        txtNgaySinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNgaySinhFocusLost(evt);
            }
        });

        cbgioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel5.setText("Điểm Trung Bình:");

        txtdiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdiemFocusLost(evt);
            }
        });

        jLabel6.setText("Đơn Vị:");

        txtdonvi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdonviFocusLost(evt);
            }
        });
        txtdonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdonviActionPerformed(evt);
            }
        });

        jLabel7.setText("Lương:");

        txtluong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtluongFocusLost(evt);
            }
        });

        jLabel8.setText("Học Phí:");

        txthocphi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txthocphiFocusLost(evt);
            }
        });

        buttonGroup1.add(rdsvhttt);
        rdsvhttt.setText("Sinh Viên HTTT");
        rdsvhttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdsvhtttActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdsvmm);
        rdsvmm.setText("Sinh Viên mật mã");
        rdsvmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdsvmmActionPerformed(evt);
            }
        });

        jLabel9.setText("Giới Tính:");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnthem)
                        .addGap(84, 84, 84)
                        .addComponent(btnluu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(rdsvhttt)
                        .addGap(18, 18, 18)
                        .addComponent(rdsvmm))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txthocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(cbgioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdsvhttt)
                    .addComponent(rdsvmm))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txthocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnluu)
                    .addComponent(btnthem))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdonviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdonviActionPerformed

    private void txtMasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasvActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
       
        String masv=txtMasv.getText();
      String hoten=txtHoten.getText();
     
        try {
             date=sdf.parse(txtNgaySinh.getText());
        } catch (ParseException ex) {
            Logger.getLogger(from.class.getName()).log(Level.SEVERE, null, ex);
        }

        
       StringBuilder sb=new StringBuilder();
     
       if(date == null ){
           sb.append("Bạn nhập sai ngày Sinh");
        }
       if(sb.length()>0){
           JOptionPane.showConfirmDialog(this,sb.toString());
       }
     String ngaySinh=sdf.format(date);

      double diem=Double.valueOf(txtdiem.getText());
    String gioiTinh= cbgioitinh.getSelectedItem().toString();
      if(rdsvhttt.isSelected()){
          
          double hocphi=Double.valueOf(txthocphi.getText());
          SinhVienHTTT svhttt=new SinhVienHTTT(hocphi, masv, hoten, ngaySinh, gioiTinh, diem);
          dsSinhVien.add(svhttt);
          int i=0;
       for(SinhVien tmp:dsSinhVien){
           if(dsSinhVien.get(i) instanceof SinhVienHTTT){
          dsSinhVien.get(i).xuat();
           }
           i++;
       }
      
      }
     else if(rdsvmm.isSelected()){
          String donvi=txtdonvi.getText();
          int luong=Integer.valueOf(txtluong.getText());
          SinhVienMatMa svmm=new SinhVienMatMa(donvi, luong, masv, hoten, ngaySinh, gioiTinh, diem);
          dsSinhVien.add(svmm);
             int i=0;
       for(SinhVien tmp:dsSinhVien){
           if(dsSinhVien.get(i) instanceof SinhVienMatMa){
          dsSinhVien.get(i).xuat();
           }
           i++;
       }
  
      }
    }//GEN-LAST:event_btnthemActionPerformed

    private void rdsvhtttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdsvhtttActionPerformed
       txtdonvi.setEnabled(false);
       txtluong.setEnabled(false);
          txthocphi.setEnabled(true);
    }//GEN-LAST:event_rdsvhtttActionPerformed

    private void rdsvmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdsvmmActionPerformed
       txthocphi.setEnabled(false);
        txtdonvi.setEnabled(true);
       txtluong.setEnabled(true);
    }//GEN-LAST:event_rdsvmmActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
       if(rdsvhttt.isSelected()){
        try (PrintWriter pw=new PrintWriter(new File("svat.dat"))){
               int i=0;
       for(SinhVien tmp:dsSinhVien){
           if(dsSinhVien.get(i) instanceof SinhVienHTTT){
         pw.println(tmp.toString());
           }
           i++;
       }
        } catch (Exception e) {
        }
       }
       else if(rdsvmm.isSelected()){
           try (PrintWriter pw=new PrintWriter(new File("svmm.dat"))){
               int i=0;
       for(SinhVien tmp:dsSinhVien){
           if(dsSinhVien.get(i) instanceof SinhVienMatMa){
         pw.println(tmp.toString());
           }
           i++;
       }
        } catch (Exception e) {
        }
       }
       StringBuilder sb=new StringBuilder();
       sb.append("đã lưu Thành Công");
       JOptionPane.showMessageDialog(this, sb.toString(),"Thông Báo",JOptionPane.OK_CANCEL_OPTION);
    }//GEN-LAST:event_btnluuActionPerformed

    private void txtMasvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMasvFocusLost
       String Masv=txtMasv.getText();
       if(Masv.equals("")){
           JOptionPane.showMessageDialog(rootPane,"Ma Sinh Viên không được để trống");
       }
    }//GEN-LAST:event_txtMasvFocusLost

    private void txtHotenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHotenFocusLost
       String Hoten=txtHoten.getText();
       if(Hoten.equals("")){
           JOptionPane.showMessageDialog(rootPane,"Họ tên không được để trống");
       }
    }//GEN-LAST:event_txtHotenFocusLost

    private void txtNgaySinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgaySinhFocusLost
        String Ngaysinh=txtNgaySinh.getText();
       if(Ngaysinh.equals("")){
           JOptionPane.showMessageDialog(rootPane,"ngày sinh không được để trống");
       }
    }//GEN-LAST:event_txtNgaySinhFocusLost

    private void txtdiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiemFocusLost
        String diem=txtdiem.getText();
       if(diem.equals("")){
           JOptionPane.showMessageDialog(rootPane,"Điểm không được để trống");
       }
    }//GEN-LAST:event_txtdiemFocusLost

    private void txtdonviFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdonviFocusLost
        String donvi=txtdonvi.getText();
       if(donvi.equals("")){
           JOptionPane.showMessageDialog(rootPane,"Đơn vị không được để trống");
       }
    }//GEN-LAST:event_txtdonviFocusLost

    private void txtluongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtluongFocusLost
       String luong=txtluong.getText();
       if(luong.equals("")){
           JOptionPane.showMessageDialog(rootPane,"Lương không được để trống");
       }
    }//GEN-LAST:event_txtluongFocusLost

    private void txthocphiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthocphiFocusLost
       String hocphi=txthocphi.getText();
       if(hocphi.equals("")){
           JOptionPane.showMessageDialog(rootPane,"học phí không được để trống");
       }
    }//GEN-LAST:event_txthocphiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

   
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
              
                new from().setVisible(true);
                Component center = null;
              new from().setLocationRelativeTo(center);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbgioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdsvhttt;
    private javax.swing.JRadioButton rdsvmm;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMasv;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txtdonvi;
    private javax.swing.JTextField txthocphi;
    private javax.swing.JTextField txtluong;
    // End of variables declaration//GEN-END:variables

    private void setngaySinh(Date parse) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
